name: align-common-xml_from_pagopa-api
on:
  push:
    branches: [develop]

jobs:
  align-common-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: ${{ github.sha }}

      - name: Checkout common-xml
        uses: actions/checkout@v2
        with:
          repository: pagopa/pagopa-nodo4-common-xml
          token: ${{ secrets.ALLOW_CLONE }} # `GitHub_PAT` is a secret that contains your PAT
          path: pagopa-nodo4-common-xml

      - name: Create new branch
        run: cd pagopa-nodo4-common-xml && git checkout -b bot_new_branch${{ steps.generate-uuid.outputs.uuid }}

      - name: Run align WSDL
        run: bash ./scripts/check_dir.sh -v -a . pagopa-nodo4-common-xml

      - name: Run align XSD
        run: bash ./scripts/check_dir.sh -v -a -e xsd . pagopa-nodo4-common-xml

      - name: Git-push branch
        run: cd pagopa-nodo4-common-xml && git config user.email "pagopateam" && git config --global user.name "pagopateam" && git add -A && git commit -a -m "update bot_new_branch${{ steps.generate-uuid.outputs.uuid }} " && git push --set-upstream origin bot_new_branch${{ steps.generate-uuid.outputs.uuid }}
